[package]
name = "salvo-project-rust"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
salvo = "0.58.3"
serde = { version = "1.0.190", features = ["derive"] }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
